[tasks.build-asi]
command = "cargo"
args = ["build", "--release"]

[tasks.build-asi-debug]
command = "cargo"
args = ["build"]

[tasks.deploy]
dependencies = ["build-asi"]
script = [
    "powershell -Command \"Copy-Item -Force target/i686-pc-windows-msvc/release/wardrobe.dll C:/Games/GTASA/wardrobe.asi\"",
    "powershell -Command \"Copy-Item -Force target/i686-pc-windows-msvc/release/wardrobe.pdb C:/Games/GTASA/wardrobe.pdb\"",
]

[tasks.debug]
dependencies = ["build-asi-debug"]
script = [
    "powershell -Command \"Copy-Item -Force target/i686-pc-windows-msvc/debug/wardrobe.dll C:/Games/GTASA/wardrobe.asi\"",
    "powershell -Command \"Copy-Item -Force target/i686-pc-windows-msvc/debug/wardrobe.pdb C:/Games/GTASA/wardrobe.pdb\"",
]

[tasks.deploy-ui]
script = [
    "powershell -Command \"New-Item -ItemType Directory -Force C:/Games/GTASA/moonloader/scripts/wardrobe_ui | Out-Null; Copy-Item -Force moonloader/wardrobe_ui/wardrobe_ui.lua C:/Games/GTASA/moonloader/scripts/wardrobe_ui/wardrobe_ui.lua\"",
]
